spring.application.name=smash_house

# Configuración del servidor
server.port=8030
server.address=0.0.0.0

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/smash_house
spring.datasource.username=postgres
spring.datasource.password=Vicioomt10297.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# JPA/Hibernate properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuración JWT
jwt.secret=unaClaveSecretaMuyLargaYSeguraParaFirmarLosTokensJWTDeSmashHouseNeiva
jwt.expiration=86400000

# Configuración SSL
server.ssl.enabled=true
# formato
server.ssl.key-store-type=PKCS12
# ubicacion
server.ssl.key-store=classpath:smashssl.p12
# contraseña
server.ssl.key-store-password=smashhouseneiva10297.
# alias
server.ssl.key-alias=smashssl

# Habilitar i18n
spring.messages.basename=messages

# Encoding para caracteres especiales en las páginas
spring.web.encoding.charset=UTF-8
spring.web.encoding.enabled=true
spring.web.encoding.force=true
spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Reporte
ranking.download.report=Descargar Reporte

# Acceder a Swagger:
# https://localhost:8030/swagger-ui/index.html